### ISSUE TITLE
Monorepo

### ISSUE THREAD

**Issue by coderaiser** [js-cst-tokens/js-grammar-estree#4]
What do you think about putting this 3 repositories into one monorepo, I see that they connected a lot, and this will simplify things a bit, everything related to `cst-tokens` will be in one place :).

**Comment by conartist6** [comment]
No.

I don't like monorepos. I think they're a terrible, terrible idea in fact, and I think the projects that adopted them are facing failure.

My argument against them is very simple: they don't evolve. It turns out that squishing things together sacrifices independence.

The most obvious way this manifests is that it becomes hard to gain and trust maintainers, because permissions and ownership are determined at the repository level. Whenever you might consider trusting somebody with a single package, you must instead trust them with everything. This is very hard to do! There is nobody I trust with the entire design of my ecosystem, not even really myself. But I could definitely find somebody I trust to maintain this particular package, and that person could find someone they trust to help, mostly because this is a specific package with a specific purpose and it is that much easier to determine that a potential maintainer's incentives are aligned with those of this package.

Essentially what I am talking about here is allowing each package to grow as a truly independent project, with its own leadership and maintainership, its own well-stated goals, its own issue tracker, and definitely its own git repo. It is a gift to the future community of maintainers to keep the git repos small, and to allow a single package to be forked without forking every other package at the same time!

I think we can build software better, and build better software. I want to build things that will last a long time, and that means planning sustainable structures that don't require me to be part of them.
